config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'collections#owned'
    end
  
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end

  resources :collections, except: %i[ index show ] do
    resources :cards, except: %i[ show ]
    resources :executions, shallow: true, only: %i[ new create show ]
    resources :favorites, only: %i[ create destroy ]
  end

  scope :collections do
    get '/public', to: 'collections#public', as: :public_collections
    get '/favorites', to: 'collections#favorites', as: :favorite_collections
    get '/owned', to: 'collections#owned', as: :owned_collections
  end

  resources :cycles, only: %i[ show update ]
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_enumeration_for :privacy, create_helpers: true
  has_enumeration_for :language, create_helpers: true
  
  validates :title, presence: true
  validates :description, presence: true
  validates :privacy, presence: true
  validates :language, presence: true

  belongs_to :user
  has_many :cards, dependent: :destroy
  has_many :executions, dependent: :destroy
  has_many :favorites, dependent: :destroy

  scope :publics, -> (user) { where(privacy: Privacy::PUBLIC).where.not(user: user) }
  scope :owned_by, -> (owner) { where(user: owner) }
  scope :favorited_by, -> (user) { joins(:favorites).where(favorites: { user: user }) }

  def execution
    Execution.find_by(
      collection: self,
      user: self.user,
      status: ExecutionStatus::RUNNING
    )
  end

  def favorited(user)
    Favorite.find_by({
      collection: self,
      user: user
    })
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_collection, only: %i[ edit update destroy ]

  def public
    @query = Collection.ransack(params[:query])
    @collections = @query.result.publics(current_user)
    @pagy, @collections = pagy(@collections.includes([:user, :cards]))
    
    @ransack_path = public_collections_path
    render 'index'
  end

  def favorites
    @query = Collection.ransack(params[:query])
    @collections = @query.result.favorited_by(current_user)
    @pagy, @collections = pagy(@collections.includes([:user, :cards]))

    @ransack_path = favorite_collections_path
    render 'index'
  end

  def owned
    @query = Collection.ransack(params[:query])
    @collections = @query.result.owned_by(current_user)
    @pagy, @collections = pagy(@collections.includes([:user, :cards]))
    
    @ransack_path = owned_collections_path
    render 'index'
  end

  def new
    @collection = Collection.new
  end

  def edit
    authorize @collection
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    
    if @collection.save
      redirect_to collections_path, notice: "Coleção criada com sucesso!"
    else
      render(
        turbo_stream: turbo_stream.replace(
          'collections_form', 
          partial: 'collections/form', 
          locals: { collection: @collection }
        )
      )
    end
  end

  def update
    authorize @collection

    if @collection.update(collection_params)
      redirect_to collections_path, notice: "Collection atualizada com sucesso!"
    else
      render(
        turbo_stream: turbo_stream.replace(
          'collections_form', 
          partial: 'collections/form', 
          locals: { collection: @collection }
        )
      )
    end
  end

  def destroy
    authorize @collection
    
    @collection.destroy
    redirect_to collections_url, notice: "Collection removida com sucesso!."
  end

  private
    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:title, :description, :privacy, :language)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id(collection) %>" class="column is-12-tablet is-6-desktop is-4-widescreen">
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        <%= collection.title %>
      </p>

      <p class="tag mx-1 my-3 is-link is-light">
        <%= collection.language %>
      </p>

      <% if collection.public? %>
        <p class="tag mx-1 my-3 is-dark">
          Public
        </p>
      <% elsif collection.private? %>
        <p class="tag mx-1 my-3 is-warning">
          Private
        </p>
      <% end %>

      <div class="dropdown is-hoverable is-right">
        <button class="card-header-icon" aria-label="more options">
          <span class="icon">
            <i class="bi bi-caret-down-fill"></i>
          </span>
        </button>
      
        <div class="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <% if policy(collection).list_cards? %>
              <%= link_to collection_cards_path(collection), class: 'dropdown-item' do %>
                <span class="icon is-small">
                  <i class="bi bi-files"></i>
                </span>
                <span>Cartas</span>
              <% end %>
            <% end %>

            <% if policy(collection).update? %>
              <%= link_to edit_collection_path(collection), data: { turbo_frame: "modal" }, class: 'dropdown-item' do %>
                <span class="icon is-small">
                  <i class="bi bi-pencil-square"></i>
                </span>
                <span>Editar</span>
              <% end %>
            <% end %>

            <% if policy(collection).destroy? %>
              <%= link_to collection_path(collection), data: { turbo_method: :delete }, class: 'dropdown-item' do %>
                <span class="icon is-small">
                  <i class="bi bi-trash2"></i>
                </span>
                <span>Remover</span>
              <% end %>
            <% end %>

            <% if collection.favorited(current_user) %>
              <%= link_to collection_favorite_path(collection, collection.favorited(current_user)), data: { turbo_method: :delete }, class: 'dropdown-item' do %>
                <span class="icon is-small">
                  <i class="bi bi-star"></i>
                </span>
                <span>Desfavoritar</span>
              <% end %>

            <% else %>
              
              <%= link_to collection_favorites_path(collection), data: { turbo_method: :post }, class: 'dropdown-item' do %>
                <span class="icon is-small">
                  <i class="bi bi-star-fill"></i>
                </span>
                <span>Favoritar</span>
              <% end %>
            <% end %>

            <% if policy(collection).start_execution?  %>
              <% if collection.execution %>
                <%= link_to collection.execution, data: { turbo_frame: "modal"}, class: 'dropdown-item' do %>
                  <span class="icon is-small">
                    <i class="bi bi-arrow-repeat"></i>
                  </span>
                  <span>Continuar</span>
                <% end %>
                
              <% else %>

                <%= link_to new_collection_execution_path(collection), data: { turbo_frame: "modal" }, class: 'dropdown-item' do %>
                  <span class="icon is-small">
                    <i class="bi bi-arrow-repeat"></i>
                  </span>
                  <span>Estudar</span>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <div class="card-content">
      <div class="content">
        <%= collection.description %>
      </div>
    </div>
  </div>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, id: "collections_form", data: { turbo_frame: "_top"}) do |form| %>
  <%= render 'shared/form_errors', resource: collection  %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="select">
    <%= form.select(:privacy, options_for_select(Privacy.to_a, collection.privacy)) %>
  </div>

  <div class="select">
    <%= form.select(:language, options_for_select(Language.to_a, collection.language)) %>
  </div>

  <div class="field is-flex is-justify-content-end">
    <%= link_to 'Cancelar', :back, class: 'button is-light mx-2' %>
    <%= form.submit class: 'button is-dark' %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <div class="block">
          <h3 class="subtitle is-3 has-text-centered">
            Editar Coleção
          </h3>
        </div>

        <hr />

        <div class="block">
          <%= render 'form', collection: @collection %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/collections/index.html.erb
<%= content_for :page_title do %>
  <% if current_page?(public_collections_path) %>
    Coleções Públicas
  <% elsif current_page?(favorite_collections_path) %>
    Coleções Favoritas
  <% elsif current_page?(owned_collections_path) %>
    Minhas Coleções
  <% end %>
<% end %>

<%= content_for :page_actions do %>
  <%= link_to new_collection_path, data: { turbo_frame: "modal" }, class: 'button is-dark' do %>
    <span class="icon">
      <i class="bi bi-plus-square"></i>
    </span>
    <span>Nova Coleção</span>
  <% end %>
<% end %>

<%= content_for :page_filter do %>
  <%= search_form_for @query, url: @ransack_path do |f| %>
    <div class="field is-flex mb-4">
      <%= f.search_field :title_cont, class: 'input' %>
      <%= f.submit class: 'ml-3 button is-link' %>
    </div>
  <% end %>
<% end %>

<% unless @collections.empty? %>
  <div class="columns is-multiline">
    <% @collections.each do |collection| %>
      <%= render 'collection', collection: collection %>
    <% end %>
  </div>
  
  <div class="is-flex is-justify-content-center">
    <%== pagy_bulma_nav(@pagy) %>
  </div>
<% else %>
  <%= render 'shared/not_found' %>
<% end %>

<%= turbo_frame_tag "modal" %>

app/views/collections/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <div class="block">
          <h3 class="subtitle is-3 has-text-centered">
            Nova Coleção
          </h3>
        </div>

        <hr />

        <div class="block">
          <%= render 'form', collection: @collection %>
        </div>
      </div>
    </div>
  </div>
<% end %>