config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'collections#owned'
    end
  
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end

  resources :collections, except: %i[ index show ] do
    resources :cards, except: %i[ show ]
    resources :executions, shallow: true, only: %i[ new create show ]
    resources :favorites, only: %i[ create destroy ]
  end

  scope :collections do
    get '/public', to: 'collections#public', as: :public_collections
    get '/favorites', to: 'collections#favorites', as: :favorite_collections
    get '/owned', to: 'collections#owned', as: :owned_collections
  end

  resources :cycles, only: %i[ show update ]
end

app/models/execution.rb
class Execution < ApplicationRecord
  has_enumeration_for :status, with: ExecutionStatus

  validates :score, presence: true
  validates :size, presence: true

  belongs_to :collection
  belongs_to :user
  belongs_to :cycle, optional: true
  
  before_create :set_default_status, :fix_size

  private

  def set_default_status
    self.status = ExecutionStatus::RUNNING
  end

  def fix_size
    cards_length = self.collection.cards.count

    if self.size > cards_length
      self.size = cards_length
    end
  end
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_collection, only: %i[ new create ]
  before_action :set_execution, only: %i[ show ]

  def show; end

  def new
    @execution = Execution.new
  end

  def create
    @execution = Execution.new(execution_params)
    @execution.user = current_user
    @execution.collection = @collection

    if @execution.save
      CyclesAlgorithm.new(
        cards: @collection.cards, 
        execution: @execution
      ).send(:random)

      redirect_to @execution
    else
      render(
        turbo_stream: turbo_stream.replace(
          'execution_form', 
          partial: 'executions/form', 
          locals: { collection: @collection, execution: @execution }
        )
      )
    end
  end

  private

  def execution_params
    params.require(:execution).permit(:size)
  end

  def set_execution
    @execution = Execution.find(params[:id])
  end

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end
end
  

app/views/executions/_form.html.erb
<%= form_with(model: [collection, execution], id: 'execution_form', data: { turbo_frame: "_top"}) do |f| %>
  <%= render 'shared/form_errors', resource: execution  %>

  <div class="field">
    <%= f.label :size, class: 'label' %>
    <%= f.number_field :size, rows: 1, class: 'textarea' %>
  </div>

  <div class="field is-flex is-justify-content-end">
    <%= link_to 'Cancelar', root_path, class: 'button is-light mx-2' %>
    <%= f.submit class: 'button is-dark' %>
  </div>
<% end %>

app/views/executions/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <div class="block">
          <h3 class="subtitle is-3 has-text-centered">
            Configurações
          </h3>
        </div>

        <hr />

        <div class="block">
          <%= render 'form', collection: @collection, execution: @execution %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/executions/show.html.erb
<div class="level" data-controller="execution">
  <div class="level-left">
    <div class="level-item">
      <h2 class="subtitle is-2">
        <%= @execution.collection.title %>
      </h2>
    </div>
  </div>

  <%= link_to 'Buscar carta', cycle_path(@execution.cycle), 
    id: 'find-first-cycle-button', 
    class: "is-hidden" 
  %>

  <div class="level-right">
    <p class="level-item">
      <progress class="progress is-small" value="3" max="<%= @execution.size %>"></progress>
    </p>
  </div>
</div>

<div class="block">
</div>

<div class="block">
  <%= turbo_frame_tag :cycle %>
</div>