config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'collections#owned'
    end
  
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end

  resources :collections, except: %i[ index show ] do
    resources :cards, except: %i[ show ]
    resources :executions, shallow: true, only: %i[ new create show ]
    resources :favorites, only: %i[ create destroy ]
  end

  scope :collections do
    get '/public', to: 'collections#public', as: :public_collections
    get '/favorites', to: 'collections#favorites', as: :favorite_collections
    get '/owned', to: 'collections#owned', as: :owned_collections
  end

  resources :cycles, only: %i[ show update ]
end

app/models/card.rb
class Card < ApplicationRecord
    validates :question, presence: true
    validates :answer, presence: true

    belongs_to :collection
    has_many :scores, dependent: :destroy
    has_many :cycles, dependent: :destroy
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collection
  before_action :set_card, only: %i[ edit update destroy ]
  
  def index
    @pagy, @cards = pagy(Card.where(collection: @collection).latest)
    authorize @collection, :list_cards?
  end

  def new
    @card = Card.new

    authorize @collection, :create_card?
  end
  
  def edit
    authorize @collection, :create_card?
  end

  def create
    @card = Card.new(card_params)
    @card.collection = @collection

    authorize @collection, :create_card?

    if @card.save
      redirect_to collection_cards_path(@collection), notice: 'Carta criada com sucesso!'
    else
      render(
        turbo_stream: turbo_stream.replace(
          'cards_form', 
          partial: 'cards/form', 
          locals: { collection: @collection, card: @card }
        )
      )
    end
  end

  def update
    authorize @collection, :create_card?

    if @card.update(card_params)
      redirect_to collection_cards_path(@collection), notice: 'Carta atualizada com sucesso!'
    else
      render(
        turbo_stream: turbo_stream.replace(
          'cards_form', 
          partial: 'cards/form', 
          locals: { collection: @collection, card: @card }
        )
      )
    end
  end

  def destroy
    authorize @collection, :create_card?

    @card.destroy
    redirect_to collection_cards_path(@collection), notice: 'Carta removida com sucesso!'
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:question, :answer)
  end
end

app/views/cards/_form.html.erb
<%= form_with(model: [collection, card], id: 'cards_form', data: { turbo_frame: "_top"}) do |f| %>
  <%= render 'shared/form_errors', resource: card  %>

  <div class="field">
    <%= f.label :question, class: 'label' %>
    <%= f.text_area :question, rows: 1, class: 'textarea' %>
  </div>

  <div class="field">
    <%= f.label :answer, class: 'label' %>
    <%= f.text_area :answer, class: 'textarea' %>
  </div>

  <div class="field is-flex is-justify-content-end">
    <%= link_to 'Cancelar', collection_cards_path(collection), class: 'button is-light mx-2' %>
    <%= f.submit class: 'button is-dark' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <div class="block">
          <h3 class="subtitle is-3 has-text-centered">
            Editar Carta
          </h3>
        </div>

        <hr />

        <div class="block">
          <%= render 'form', collection: @collection, card: @card %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/index.html.erb
<%= content_for :page_title do %>
  Cartas - <%= @collection.title %>
<% end %>

<% if policy(@collection).create_card? %>
  <%= content_for :page_actions do %>
    <%= link_to new_collection_card_path(@collection), data: { turbo_frame: "modal" }, class: 'button is-dark' do %>
      <span class="icon">
        <i class="bi bi-plus-square"></i>
      </span>
      <span>Nova Carta</span>
    <% end %>
  <% end %>
<% end %>

<% unless @cards.empty? %>
  <table class="table is-fullwidth is-hoverable is-bordered">
    <thead>
      <tr>
        <th>Questão</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |card| %>
        <tr id="<%= dom_id(card) %>">
          <td><%= card.question %></td>
          <td>
            <% if policy(card).actions? %>
              <div class="dropdown is-hoverable">
                <div class="dropdown-trigger">
                  <button class="button" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Ação</span>
                    <span class="icon is-small">
                      <i class="bi bi-caret-down-fill"></i>
                    </span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu3" role="menu">
                  <div class="dropdown-content">
                    <% if policy(card).update? %>
                      <%= link_to edit_collection_card_path(@collection, card), data: { turbo_frame: "modal" }, class: 'dropdown-item' do %>
                        <span class="icon is-small">
                          <i class="bi bi-pencil-square"></i>
                        </span>
                        <span>Editar</span>
                      <% end %>
                    <% end %>

                    <% if policy(card).destroy? %>
                      <%= link_to collection_card_path(@collection, card), data: { turbo_method: :delete }, class: 'dropdown-item' do %>
                        <span class="icon is-small">
                          <i class="bi bi-trash2"></i>
                        </span>
                        <span>Remover</span>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% else %>
              <i>Sem Ações</i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr />

  <div class="is-flex is-justify-content-center">
    <%== pagy_bulma_nav(@pagy) %>
  </div>
<% else %>
  <%= render 'shared/not_found' %>
<% end %>

<%= turbo_frame_tag "modal" %>

app/views/cards/new.html.erb
<%= turbo_frame_tag "modal" do %>
<div class="modal is-active">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box">
      <div class="block">
        <h3 class="subtitle is-3 has-text-centered">
          Nova Carta
        </h3>
      </div>

      <hr />

      <div class="block">
        <%= render 'form', collection: @collection, card: @card %>
      </div>
    </div>
  </div>
</div>
<% end %>