config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'collections#owned'
    end
  
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end

  resources :collections, except: %i[ index show ] do
    resources :cards, except: %i[ show ]
    resources :executions, shallow: true, only: %i[ new create show ]
    resources :favorites, only: %i[ create destroy ]
  end

  scope :collections do
    get '/public', to: 'collections#public', as: :public_collections
    get '/favorites', to: 'collections#favorites', as: :favorite_collections
    get '/owned', to: 'collections#owned', as: :owned_collections
  end

  resources :cycles, only: %i[ show update ]
end

app/views/layouts/_flashmessage.html.erb
<% if alert %>
  <div class="notification is-danger is-light">
    <p><%= alert %></p>
  </div>
<% end %>

<% if notice %>
  <div class="notification is-success is-light">
    <p><%= notice %></p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar has-shadow" data-controller="navbar">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to 'Cards App', root_path, class: 'title is-2 navbar-item' %>
    
      <a class="navbar-burger" data-navbar-target="navburger">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu" data-navbar-target="navmenu">
      <div class="navbar-end">
        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <span class="navbar-link">
              Minha Conta
            </span>
            <div class="navbar-dropdown is-boxed">
              <%= link_to edit_user_registration_path, class: 'navbar-item' do %>
                Configurar conta
              <% end %>
              
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'navbar-item' do %>
                Sair
              <% end %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path, class: 'navbar-item' %>
          <%= link_to 'Criar conta', new_user_registration_path, class: 'navbar-item' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="column is-4-tablet is-3-desktop is-2-widescreen">
  <aside data-controller="sidebar" class="box menu">
    <p class="menu-label">
      Coleções
    </p>
    <ul class="menu-list">
      <li>
        <%= link_to 'Minhas', owned_collections_path %>
      </li>
      <li>
        <%= link_to 'Favoritas', favorite_collections_path %>
      </li>
      <li>
        <%= link_to 'Públicas', public_collections_path %>
      </li>
    </ul>
  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
  
    <main class="container">
      <div class="my-5">
        <%= render 'layouts/flashmessage' %>
      </div>

      <%# --- page top content --- %>
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <h2 class="subtitle is-2">
              <%= yield :page_title %>
            </h2>
          </div>
        </div>

        <div class="level-right">
          <p class="level-item">
            <%= yield :page_actions %>
          </p>
        </div>
      </div>
      <%# --- page top content --- %>

      <div class="columns">
        <% if user_signed_in? %>
          <%= render 'layouts/sidebar' %>
        <% end %>

        <div class="column">
          <%= yield :page_filter %>

          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>